name: SlimeGlue
version: '${project.version}'
main: com.xzavier0722.mc.plugin.slimeglue.SlimeGlue
api-version: 1.13
depend: [ Slimefun ]
folia-supported: true
softdepend:
  - Kingdoms
  - Quickshop
  - QuickShop-Hikari
  - Magic
  - LockettePro
authors: [ Xzavier0722 ]
description: A Slimefun addon, target to improve the compatibility with other plugins
website: https://github.com/Xzavier0722/SlimeGlue
